### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by BrianHicks** [BrianHicks/finch#14]
Say I have a couple of common tasks. Things like making sure a deployment is done for $dayjob (checking data, different account tests, etc). I can add tasks each time to "make sure it's done" but that's not estimable, chunkable, or delegatable. So I'd like to be able to get a finer grain without sacrificing the ease of adding a single thing. So, workflows.

New commands:

```
$ finch workflow-add name # adds a new workflow document
$ finch workflow-edit name # edits an existing workflow document
$ finch workflow-delete name
$ finch workflow-render name # adds the tasks in the workflow... obviously needs a better name
```

Here's how a parsed workflow template could look:

``` toml
[template]
name="create-release"
description="Create a release for a software package"

[[question]]
id=name
text="What is the package's name?"

[[question]]
id=version
text="What version are you releasing?"
validate="\d+\.\d+\.\d+"

[[task]]
template="Create {{version}} release branch for {{name}}"
delay=P1D

[[task]]
template="Review any issues left for {{version}} of {{name}}"
```
